# Generated by Django 4.0.3 on 2022-03-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso'),
        ),
    ]
